### ISSUE TITLE
Ignoring a json array

### ISSUE THREAD

**Issue by sarge** [achiu/rack-parser#13]
Hello,

We are using this as middleware for a sinatra application. On some apis we pass a json object ```{ "a": "value"}``` on other apis we pass ```[{"a":"value1"}, {"a":"value2"}]```

In the json object syntax everything is fine, in the case of a json array being passed rack expects to be able to call merge.

```
  no implicit conversion of Array into Hash
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/request.rb:230:in `merge'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/request.rb:230:in `params'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:893:in `call!'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
     # ./models/rack_parser.rb:35:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-test-0.6.3/lib/rack/mock_session.rb:31:in `request'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/sarge/.rvm/gems/ruby-2.0.0-p247@shift72/gems/rack-test-0.6.3/lib/rack/test.rb:76:in `put'
```

What are your thoughts on only setting the FORM_HASH and FORM_INPUT if the parsed value is a hash, the expectation is that in this case the params is not the pattern to use when dealing with an array of items being PUT, and would need to be dealt with by accessing the body directly.

```
def call(env)
      type   = Rack::Request.new(env).media_type
      parser = parsers.detect { |content_type, _| type.match(content_type) } if type
      return @app.call(env) unless parser
      body = env[POST_BODY].read ; env[POST_BODY].rewind
      return @app.call(env) unless body && !body.empty?
      begin
        parsed = parser.last.call body

        # suggested update
        env.update FORM_HASH => parsed, FORM_INPUT => env[POST_BODY] if parsed.is_a?(Hash)


      rescue StandardError => e
        warn! e, type
        handler   = handlers.detect { |content_type, _|  type.match(content_type) }
        handler ||= ['default', ERROR_HANDLER]
        return handler.last.call(e, type)
      end
      @app.call env
    end
```

**Comment by lksv** [comment]
:+1: 

furthermore event if the JSON data are Array I would like to get the parsed result, e.g.

     RACK_RESULT = 'rack.parser.result'
     # ...
     if parsed.kind_of(Hash)
       env.update FORM_HASH => parsed, FORM_INPUT => env[POST_BODY], RACK_RESULT => parsed
     else
       env[RACK_RESULT] = parser
     end

**Comment by sarge** [comment]
Good suggestion, at the moment I am double handling this.

**Comment by achiu** [comment]
closing this since #14 is merged and handles this issue.
